name: Generate m3u8 Files

on:
  push:
    paths:
      - "channels.json"
      - "generate.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Generator Script
        run: python generate.py

      - name: Commit and push each .m3u8 file separately
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git reset --hard origin/main

          # Loop through all .m3u8 files generated
          for file in *.m3u8; do
            # Check if file exists and has changes
            if git status --porcelain | grep -q "$file"; then
              git add "$file"
              git commit -m "$file"
              git push
            else
              echo "No changes in $file"
            fi
          done
